Google-clone
Stevenkwizera06/google-clone pull request #1
Opened 2022-11-14 19:11 UTC by Stevenkwizera06

###What does this PR do?
shows the cloning of the homepage of google

###Description of Task to be completed?
the Google word needs to stay always at the center of the page as the page expands or shrinks

###How should this be manually tested?

Clone the repo
- checkout to branch ft-dev
- run npm run dev

2022-11-15 17:14 UTC, MugaboDenys requested changes

2022-11-15 17:14 UTC, MugaboDenys commented on index.html
>          <svg class="w-6 fill-secondary_dark" viewBox="0 0 24 24">
Here you should try to use svg from a file not codes

2022-11-16 14:34 UTC, MugaboDenys approved these changes

2022-11-16 14:55 UTC, Ntwali-Josue requested changes
Hey, @Stevenkwizera06 Check down below the reviews on your work.

2022-11-16 14:55 UTC, Ntwali-Josue commented on index.html
> +          <div class="flex ">
Try to imitate the spacing and the sizes of the original google input icons as close as you can.

your design: 
![image](https://user-images.githubusercontent.com/58233753/202210193-a65235a4-c059-403b-97ec-af9dc5eff913.png)

Google design: 
![image](https://user-images.githubusercontent.com/58233753/202210272-c58def95-8ef3-4a6a-99f7-836ff9eb8706.png)

2022-11-16 14:55 UTC, Ntwali-Josue commented on index.html
> +      </div>
Changing the background of these buttons once they are hovered on, is not really needed, only change the border styles, once a button is hovered.

2022-11-16 14:55 UTC, Ntwali-Josue commented on index.html
> +          <input type="text" class="w-96 border-none outline-none text-white text-base bg-transparent ml-12">
Try to reduce the size of the input field and also add a camera icon on the mobile devices, check the differences between your design and the original one

Yours: 
![image](https://user-images.githubusercontent.com/58233753/202213055-7213f324-8445-4285-9793-d751615847ba.png)
Google: 
![image](https://user-images.githubusercontent.com/58233753/202212882-76f2c8ab-574f-4f3f-968e-c879f097ecf5.png)

2022-11-16 14:55 UTC, Ntwali-Josue commented on images/micro.html
> +<!DOCTYPE html>
You can remove this file, since it's not being used.

2022-11-16 17:02 UTC, Ntwali-Josue approved these changes

2022-11-21 11:42 UTC, Morrism1 requested changes
Looks Good. One change in the config.

2022-11-21 11:42 UTC, Morrism1 commented on tailwind.config.js
> +        xsm: '0.813rem',
Can you check how Tailwind name their content and follow it accordingly.

2022-11-29 20:56 UTC, Morrism1 approved these changes
LGTM!

2022-12-01 06:34 UTC, merged